package org.telegram.messenger.audioinfo.mp3;

public enum ID3v1Genre {
    public static final enum ID3v1Genre ACapella;
    public static final enum ID3v1Genre Acid;
    public static final enum ID3v1Genre AcidJazz;
    public static final enum ID3v1Genre AcidPunk;
    public static final enum ID3v1Genre Acoustic;
    public static final enum ID3v1Genre AlternRock;
    public static final enum ID3v1Genre Alternative;
    public static final enum ID3v1Genre Ambient;
    public static final enum ID3v1Genre Avantgarde;
    public static final enum ID3v1Genre Ballad;
    public static final enum ID3v1Genre Bass;
    public static final enum ID3v1Genre Bebop;
    public static final enum ID3v1Genre BigBand;
    public static final enum ID3v1Genre Bluegrass;
    public static final enum ID3v1Genre Blues;
    public static final enum ID3v1Genre BootyBass;
    public static final enum ID3v1Genre Cabaret;
    public static final enum ID3v1Genre Celtic;
    public static final enum ID3v1Genre ChamberMusic;
    public static final enum ID3v1Genre Chanson;
    public static final enum ID3v1Genre Chorus;
    public static final enum ID3v1Genre ChristianRap;
    public static final enum ID3v1Genre ClassicRock;
    public static final enum ID3v1Genre Classical;
    public static final enum ID3v1Genre Club;
    public static final enum ID3v1Genre Comedy;
    public static final enum ID3v1Genre Country;
    public static final enum ID3v1Genre Cult;
    public static final enum ID3v1Genre Dance;
    public static final enum ID3v1Genre DanceHall;
    public static final enum ID3v1Genre Darkwave;
    public static final enum ID3v1Genre DeathMetal;
    public static final enum ID3v1Genre Disco;
    public static final enum ID3v1Genre Dream;
    public static final enum ID3v1Genre DrumSolo;
    public static final enum ID3v1Genre Duet;
    public static final enum ID3v1Genre EasyListening;
    public static final enum ID3v1Genre Electronic;
    public static final enum ID3v1Genre Ethnic;
    public static final enum ID3v1Genre EuroHouse;
    public static final enum ID3v1Genre EuroTechno;
    public static final enum ID3v1Genre Eurodance;
    public static final enum ID3v1Genre FastFusion;
    public static final enum ID3v1Genre Folk;
    public static final enum ID3v1Genre FolkRock;
    public static final enum ID3v1Genre Folklore;
    public static final enum ID3v1Genre Freestyle;
    public static final enum ID3v1Genre Funk;
    public static final enum ID3v1Genre Fusion;
    public static final enum ID3v1Genre Game;
    public static final enum ID3v1Genre Gangsta;
    public static final enum ID3v1Genre Gospel;
    public static final enum ID3v1Genre Gothic;
    public static final enum ID3v1Genre GothicRock;
    public static final enum ID3v1Genre Grunge;
    public static final enum ID3v1Genre HardRock;
    public static final enum ID3v1Genre HipHop;
    public static final enum ID3v1Genre House;
    public static final enum ID3v1Genre Humour;
    public static final enum ID3v1Genre Industrial;
    public static final enum ID3v1Genre Instrumental;
    public static final enum ID3v1Genre InstrumentalPop;
    public static final enum ID3v1Genre InstrumentalRock;
    public static final enum ID3v1Genre Jazz;
    public static final enum ID3v1Genre JazzFunk;
    public static final enum ID3v1Genre Jungle;
    public static final enum ID3v1Genre Latin;
    public static final enum ID3v1Genre LoFi;
    public static final enum ID3v1Genre Meditative;
    public static final enum ID3v1Genre Metal;
    public static final enum ID3v1Genre Musical;
    public static final enum ID3v1Genre NationalFolk;
    public static final enum ID3v1Genre NativeAmerican;
    public static final enum ID3v1Genre NewAge;
    public static final enum ID3v1Genre NewWave;
    public static final enum ID3v1Genre Noise;
    public static final enum ID3v1Genre Oldies;
    public static final enum ID3v1Genre Opera;
    public static final enum ID3v1Genre Other;
    public static final enum ID3v1Genre Polka;
    public static final enum ID3v1Genre Pop;
    public static final enum ID3v1Genre PopFolk;
    public static final enum ID3v1Genre PopFunk;
    public static final enum ID3v1Genre PornGroove;
    public static final enum ID3v1Genre PowerBallad;
    public static final enum ID3v1Genre Pranks;
    public static final enum ID3v1Genre Primus;
    public static final enum ID3v1Genre ProgressiveRock;
    public static final enum ID3v1Genre Psychadelic;
    public static final enum ID3v1Genre PsychedelicRock;
    public static final enum ID3v1Genre Punk;
    public static final enum ID3v1Genre PunkRock;
    public static final enum ID3v1Genre Rap;
    public static final enum ID3v1Genre Rave;
    public static final enum ID3v1Genre Reggae;
    public static final enum ID3v1Genre Retro;
    public static final enum ID3v1Genre Revival;
    public static final enum ID3v1Genre RhytmicSoul;
    public static final enum ID3v1Genre RnB;
    public static final enum ID3v1Genre Rock;
    public static final enum ID3v1Genre RockAndRoll;
    public static final enum ID3v1Genre Samba;
    public static final enum ID3v1Genre Satire;
    public static final enum ID3v1Genre Showtunes;
    public static final enum ID3v1Genre Ska;
    public static final enum ID3v1Genre SlowJam;
    public static final enum ID3v1Genre SlowRock;
    public static final enum ID3v1Genre Sonata;
    public static final enum ID3v1Genre Soul;
    public static final enum ID3v1Genre SoundClip;
    public static final enum ID3v1Genre Soundtrack;
    public static final enum ID3v1Genre SouthernRock;
    public static final enum ID3v1Genre Space;
    public static final enum ID3v1Genre Speech;
    public static final enum ID3v1Genre Swing;
    public static final enum ID3v1Genre SymphonicRock;
    public static final enum ID3v1Genre Symphony;
    public static final enum ID3v1Genre Tango;
    public static final enum ID3v1Genre Techno;
    public static final enum ID3v1Genre TechnoIndustrial;
    public static final enum ID3v1Genre Top40;
    public static final enum ID3v1Genre Trailer;
    public static final enum ID3v1Genre Trance;
    public static final enum ID3v1Genre Tribal;
    public static final enum ID3v1Genre TripHop;
    public static final enum ID3v1Genre Vocal;
    private final String description;

    static {
        ID3v1Genre.Blues = new ID3v1Genre("Blues", 0, "Blues");
        ID3v1Genre.ClassicRock = new ID3v1Genre("ClassicRock", 1, "Classic Rock");
        ID3v1Genre.Country = new ID3v1Genre("Country", 2, "Country");
        ID3v1Genre.Dance = new ID3v1Genre("Dance", 3, "Dance");
        ID3v1Genre.Disco = new ID3v1Genre("Disco", 4, "Disco");
        ID3v1Genre.Funk = new ID3v1Genre("Funk", 5, "Funk");
        ID3v1Genre.Grunge = new ID3v1Genre("Grunge", 6, "Grunge");
        ID3v1Genre.HipHop = new ID3v1Genre("HipHop", 7, "Hip-Hop");
        ID3v1Genre.Jazz = new ID3v1Genre("Jazz", 8, "Jazz");
        ID3v1Genre.Metal = new ID3v1Genre("Metal", 9, "Metal");
        ID3v1Genre.NewAge = new ID3v1Genre("NewAge", 10, "New Age");
        ID3v1Genre.Oldies = new ID3v1Genre("Oldies", 11, "Oldies");
        ID3v1Genre.Other = new ID3v1Genre("Other", 12, "Other");
        ID3v1Genre.Pop = new ID3v1Genre("Pop", 13, "Pop");
        ID3v1Genre.RnB = new ID3v1Genre("RnB", 14, "R&B");
        ID3v1Genre.Rap = new ID3v1Genre("Rap", 15, "Rap");
        ID3v1Genre.Reggae = new ID3v1Genre("Reggae", 16, "Reggae");
        ID3v1Genre.Rock = new ID3v1Genre("Rock", 17, "Rock");
        ID3v1Genre.Techno = new ID3v1Genre("Techno", 18, "Techno");
        ID3v1Genre.Industrial = new ID3v1Genre("Industrial", 19, "Industrial");
        ID3v1Genre.Alternative = new ID3v1Genre("Alternative", 20, "Alternative");
        ID3v1Genre.Ska = new ID3v1Genre("Ska", 21, "Ska");
        ID3v1Genre.DeathMetal = new ID3v1Genre("DeathMetal", 22, "Death Metal");
        ID3v1Genre.Pranks = new ID3v1Genre("Pranks", 23, "Pranks");
        ID3v1Genre.Soundtrack = new ID3v1Genre("Soundtrack", 24, "Soundtrack");
        ID3v1Genre.EuroTechno = new ID3v1Genre("EuroTechno", 25, "Euro-Techno");
        ID3v1Genre.Ambient = new ID3v1Genre("Ambient", 26, "Ambient");
        ID3v1Genre.TripHop = new ID3v1Genre("TripHop", 27, "Trip-Hop");
        ID3v1Genre.Vocal = new ID3v1Genre("Vocal", 28, "Vocal");
        ID3v1Genre.JazzFunk = new ID3v1Genre("JazzFunk", 29, "Jazz+Funk");
        ID3v1Genre.Fusion = new ID3v1Genre("Fusion", 30, "Fusion");
        ID3v1Genre.Trance = new ID3v1Genre("Trance", 31, "Trance");
        ID3v1Genre.Classical = new ID3v1Genre("Classical", 32, "Classical");
        ID3v1Genre.Instrumental = new ID3v1Genre("Instrumental", 33, "Instrumental");
        ID3v1Genre.Acid = new ID3v1Genre("Acid", 34, "Acid");
        ID3v1Genre.House = new ID3v1Genre("House", 35, "House");
        ID3v1Genre.Game = new ID3v1Genre("Game", 36, "Game");
        ID3v1Genre.SoundClip = new ID3v1Genre("SoundClip", 37, "Sound Clip");
        ID3v1Genre.Gospel = new ID3v1Genre("Gospel", 38, "Gospel");
        ID3v1Genre.Noise = new ID3v1Genre("Noise", 39, "Noise");
        ID3v1Genre.AlternRock = new ID3v1Genre("AlternRock", 40, "AlternRock");
        ID3v1Genre.Bass = new ID3v1Genre("Bass", 41, "Bass");
        ID3v1Genre.Soul = new ID3v1Genre("Soul", 42, "Soul");
        ID3v1Genre.Punk = new ID3v1Genre("Punk", 43, "Punk");
        ID3v1Genre.Space = new ID3v1Genre("Space", 44, "Space");
        ID3v1Genre.Meditative = new ID3v1Genre("Meditative", 45, "Meditative");
        ID3v1Genre.InstrumentalPop = new ID3v1Genre("InstrumentalPop", 46, "Instrumental Pop");
        ID3v1Genre.InstrumentalRock = new ID3v1Genre("InstrumentalRock", 47, "Instrumental Rock");
        ID3v1Genre.Ethnic = new ID3v1Genre("Ethnic", 48, "Ethnic");
        ID3v1Genre.Gothic = new ID3v1Genre("Gothic", 49, "Gothic");
        ID3v1Genre.Darkwave = new ID3v1Genre("Darkwave", 50, "Darkwave");
        ID3v1Genre.TechnoIndustrial = new ID3v1Genre("TechnoIndustrial", 51, "Techno-Industrial");
        ID3v1Genre.Electronic = new ID3v1Genre("Electronic", 52, "Electronic");
        ID3v1Genre.PopFolk = new ID3v1Genre("PopFolk", 53, "Pop-Folk");
        ID3v1Genre.Eurodance = new ID3v1Genre("Eurodance", 54, "Eurodance");
        ID3v1Genre.Dream = new ID3v1Genre("Dream", 55, "Dream");
        ID3v1Genre.SouthernRock = new ID3v1Genre("SouthernRock", 56, "Southern Rock");
        ID3v1Genre.Comedy = new ID3v1Genre("Comedy", 57, "Comedy");
        ID3v1Genre.Cult = new ID3v1Genre("Cult", 58, "Cult");
        ID3v1Genre.Gangsta = new ID3v1Genre("Gangsta", 59, "Gangsta");
        ID3v1Genre.Top40 = new ID3v1Genre("Top40", 60, "Top 40");
        ID3v1Genre.ChristianRap = new ID3v1Genre("ChristianRap", 61, "Christian Rap");
        ID3v1Genre.PopFunk = new ID3v1Genre("PopFunk", 62, "Pop/Funk");
        ID3v1Genre.Jungle = new ID3v1Genre("Jungle", 63, "Jungle");
        ID3v1Genre.NativeAmerican = new ID3v1Genre("NativeAmerican", 64, "Native American");
        ID3v1Genre.Cabaret = new ID3v1Genre("Cabaret", 65, "Cabaret");
        ID3v1Genre.NewWave = new ID3v1Genre("NewWave", 66, "New Wave");
        ID3v1Genre.Psychadelic = new ID3v1Genre("Psychadelic", 67, "Psychadelic");
        ID3v1Genre.Rave = new ID3v1Genre("Rave", 68, "Rave");
        ID3v1Genre.Showtunes = new ID3v1Genre("Showtunes", 69, "Showtunes");
        ID3v1Genre.Trailer = new ID3v1Genre("Trailer", 70, "Trailer");
        ID3v1Genre.LoFi = new ID3v1Genre("LoFi", 71, "Lo-Fi");
        ID3v1Genre.Tribal = new ID3v1Genre("Tribal", 72, "Tribal");
        ID3v1Genre.AcidPunk = new ID3v1Genre("AcidPunk", 73, "Acid Punk");
        ID3v1Genre.AcidJazz = new ID3v1Genre("AcidJazz", 74, "Acid Jazz");
        ID3v1Genre.Polka = new ID3v1Genre("Polka", 75, "Polka");
        ID3v1Genre.Retro = new ID3v1Genre("Retro", 76, "Retro");
        ID3v1Genre.Musical = new ID3v1Genre("Musical", 77, "Musical");
        ID3v1Genre.RockAndRoll = new ID3v1Genre("RockAndRoll", 78, "Rock & Roll");
        ID3v1Genre.HardRock = new ID3v1Genre("HardRock", 79, "Hard Rock");
        ID3v1Genre.Folk = new ID3v1Genre("Folk", 80, "Folk");
        ID3v1Genre.FolkRock = new ID3v1Genre("FolkRock", 81, "Folk-Rock");
        ID3v1Genre.NationalFolk = new ID3v1Genre("NationalFolk", 82, "National Folk");
        ID3v1Genre.Swing = new ID3v1Genre("Swing", 83, "Swing");
        ID3v1Genre.FastFusion = new ID3v1Genre("FastFusion", 84, "Fast Fusion");
        ID3v1Genre.Bebop = new ID3v1Genre("Bebop", 85, "Bebop");
        ID3v1Genre.Latin = new ID3v1Genre("Latin", 86, "Latin");
        ID3v1Genre.Revival = new ID3v1Genre("Revival", 87, "Revival");
        ID3v1Genre.Celtic = new ID3v1Genre("Celtic", 88, "Celtic");
        ID3v1Genre.Bluegrass = new ID3v1Genre("Bluegrass", 89, "Bluegrass");
        ID3v1Genre.Avantgarde = new ID3v1Genre("Avantgarde", 90, "Avantgarde");
        ID3v1Genre.GothicRock = new ID3v1Genre("GothicRock", 91, "Gothic Rock");
        ID3v1Genre.ProgressiveRock = new ID3v1Genre("ProgressiveRock", 92, "Progressive Rock");
        ID3v1Genre.PsychedelicRock = new ID3v1Genre("PsychedelicRock", 93, "Psychedelic Rock");
        ID3v1Genre.SymphonicRock = new ID3v1Genre("SymphonicRock", 94, "Symphonic Rock");
        ID3v1Genre.SlowRock = new ID3v1Genre("SlowRock", 95, "Slow Rock");
        ID3v1Genre.BigBand = new ID3v1Genre("BigBand", 96, "Big Band");
        ID3v1Genre.Chorus = new ID3v1Genre("Chorus", 97, "Chorus");
        ID3v1Genre.EasyListening = new ID3v1Genre("EasyListening", 98, "Easy Listening");
        ID3v1Genre.Acoustic = new ID3v1Genre("Acoustic", 99, "Acoustic");
        ID3v1Genre.Humour = new ID3v1Genre("Humour", 100, "Humour");
        ID3v1Genre.Speech = new ID3v1Genre("Speech", 101, "Speech");
        ID3v1Genre.Chanson = new ID3v1Genre("Chanson", 102, "Chanson");
        ID3v1Genre.Opera = new ID3v1Genre("Opera", 103, "Opera");
        ID3v1Genre.ChamberMusic = new ID3v1Genre("ChamberMusic", 104, "Chamber Music");
        ID3v1Genre.Sonata = new ID3v1Genre("Sonata", 105, "Sonata");
        ID3v1Genre.Symphony = new ID3v1Genre("Symphony", 106, "Symphony");
        ID3v1Genre.BootyBass = new ID3v1Genre("BootyBass", 107, "Booty Bass");
        ID3v1Genre.Primus = new ID3v1Genre("Primus", 108, "Primus");
        ID3v1Genre.PornGroove = new ID3v1Genre("PornGroove", 109, "Porn Groove");
        ID3v1Genre.Satire = new ID3v1Genre("Satire", 110, "Satire");
        ID3v1Genre.SlowJam = new ID3v1Genre("SlowJam", 111, "Slow Jam");
        ID3v1Genre.Club = new ID3v1Genre("Club", 112, "Club");
        ID3v1Genre.Tango = new ID3v1Genre("Tango", 113, "Tango");
        ID3v1Genre.Samba = new ID3v1Genre("Samba", 114, "Samba");
        ID3v1Genre.Folklore = new ID3v1Genre("Folklore", 115, "Folklore");
        ID3v1Genre.Ballad = new ID3v1Genre("Ballad", 116, "Ballad");
        ID3v1Genre.PowerBallad = new ID3v1Genre("PowerBallad", 117, "Power Ballad");
        ID3v1Genre.RhytmicSoul = new ID3v1Genre("RhytmicSoul", 118, "Rhythmic Soul");
        ID3v1Genre.Freestyle = new ID3v1Genre("Freestyle", 119, "Freestyle");
        ID3v1Genre.Duet = new ID3v1Genre("Duet", 120, "Duet");
        ID3v1Genre.PunkRock = new ID3v1Genre("PunkRock", 121, "Punk Rock");
        ID3v1Genre.DrumSolo = new ID3v1Genre("DrumSolo", 122, "Drum Solo");
        ID3v1Genre.ACapella = new ID3v1Genre("ACapella", 123, "A capella");
        ID3v1Genre.EuroHouse = new ID3v1Genre("EuroHouse", 124, "Euro-House");
        ID3v1Genre.DanceHall = new ID3v1Genre("DanceHall", 125, "Dance Hall");
        ID3v1Genre.$VALUES = new ID3v1Genre[]{ID3v1Genre.Blues, ID3v1Genre.ClassicRock, ID3v1Genre.Country, ID3v1Genre.Dance, ID3v1Genre.Disco, ID3v1Genre.Funk, ID3v1Genre.Grunge, ID3v1Genre.HipHop, ID3v1Genre.Jazz, ID3v1Genre.Metal, ID3v1Genre.NewAge, ID3v1Genre.Oldies, ID3v1Genre.Other, ID3v1Genre.Pop, ID3v1Genre.RnB, ID3v1Genre.Rap, ID3v1Genre.Reggae, ID3v1Genre.Rock, ID3v1Genre.Techno, ID3v1Genre.Industrial, ID3v1Genre.Alternative, ID3v1Genre.Ska, ID3v1Genre.DeathMetal, ID3v1Genre.Pranks, ID3v1Genre.Soundtrack, ID3v1Genre.EuroTechno, ID3v1Genre.Ambient, ID3v1Genre.TripHop, ID3v1Genre.Vocal, ID3v1Genre.JazzFunk, ID3v1Genre.Fusion, ID3v1Genre.Trance, ID3v1Genre.Classical, ID3v1Genre.Instrumental, ID3v1Genre.Acid, ID3v1Genre.House, ID3v1Genre.Game, ID3v1Genre.SoundClip, ID3v1Genre.Gospel, ID3v1Genre.Noise, ID3v1Genre.AlternRock, ID3v1Genre.Bass, ID3v1Genre.Soul, ID3v1Genre.Punk, ID3v1Genre.Space, ID3v1Genre.Meditative, ID3v1Genre.InstrumentalPop, ID3v1Genre.InstrumentalRock, ID3v1Genre.Ethnic, ID3v1Genre.Gothic, ID3v1Genre.Darkwave, ID3v1Genre.TechnoIndustrial, ID3v1Genre.Electronic, ID3v1Genre.PopFolk, ID3v1Genre.Eurodance, ID3v1Genre.Dream, ID3v1Genre.SouthernRock, ID3v1Genre.Comedy, ID3v1Genre.Cult, ID3v1Genre.Gangsta, ID3v1Genre.Top40, ID3v1Genre.ChristianRap, ID3v1Genre.PopFunk, ID3v1Genre.Jungle, ID3v1Genre.NativeAmerican, ID3v1Genre.Cabaret, ID3v1Genre.NewWave, ID3v1Genre.Psychadelic, ID3v1Genre.Rave, ID3v1Genre.Showtunes, ID3v1Genre.Trailer, ID3v1Genre.LoFi, ID3v1Genre.Tribal, ID3v1Genre.AcidPunk, ID3v1Genre.AcidJazz, ID3v1Genre.Polka, ID3v1Genre.Retro, ID3v1Genre.Musical, ID3v1Genre.RockAndRoll, ID3v1Genre.HardRock, ID3v1Genre.Folk, ID3v1Genre.FolkRock, ID3v1Genre.NationalFolk, ID3v1Genre.Swing, ID3v1Genre.FastFusion, ID3v1Genre.Bebop, ID3v1Genre.Latin, ID3v1Genre.Revival, ID3v1Genre.Celtic, ID3v1Genre.Bluegrass, ID3v1Genre.Avantgarde, ID3v1Genre.GothicRock, ID3v1Genre.ProgressiveRock, ID3v1Genre.PsychedelicRock, ID3v1Genre.SymphonicRock, ID3v1Genre.SlowRock, ID3v1Genre.BigBand, ID3v1Genre.Chorus, ID3v1Genre.EasyListening, ID3v1Genre.Acoustic, ID3v1Genre.Humour, ID3v1Genre.Speech, ID3v1Genre.Chanson, ID3v1Genre.Opera, ID3v1Genre.ChamberMusic, ID3v1Genre.Sonata, ID3v1Genre.Symphony, ID3v1Genre.BootyBass, ID3v1Genre.Primus, ID3v1Genre.PornGroove, ID3v1Genre.Satire, ID3v1Genre.SlowJam, ID3v1Genre.Club, ID3v1Genre.Tango, ID3v1Genre.Samba, ID3v1Genre.Folklore, ID3v1Genre.Ballad, ID3v1Genre.PowerBallad, ID3v1Genre.RhytmicSoul, ID3v1Genre.Freestyle, ID3v1Genre.Duet, ID3v1Genre.PunkRock, ID3v1Genre.DrumSolo, ID3v1Genre.ACapella, ID3v1Genre.EuroHouse, ID3v1Genre.DanceHall};
    }

    private ID3v1Genre(String arg1, int arg2, String arg3) {
        super(arg1, arg2);
        this.description = arg3;
    }

    public String getDescription() {
        return this.description;
    }

    public static ID3v1Genre getGenre(int arg2) {
        ID3v1Genre[] v0 = ID3v1Genre.values();
        ID3v1Genre v2 = arg2 < 0 || arg2 >= v0.length ? null : v0[arg2];
        return v2;
    }

    public int getId() {
        return this.ordinal();
    }

    public static ID3v1Genre valueOf(String arg1) {
        return Enum.valueOf(ID3v1Genre.class, arg1);
    }

    public static ID3v1Genre[] values() {
        // Method was not decompiled
    }
}

